Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |p|
        p.name = "worker2-k8s"
        p.memory = 2048
        p.cpus = 2
  end
  config.vm.hostname = "worker2-k8s"
  config.vm.network :forwarded_port, guest: 22, host: 3202, id: 'ssh'
  config.vm.network "public_network", ip: "192.168.0.52", bridge: "enp34s0"


  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install net-tools vim curl -y
  curl -fsSL https://get.docker.com/ | bash
  cat > /etc/docker/daemon.json <<EOF
 {
 "exec-opts": ["native.cgroupdriver=systemd"],
 "log-driver": "json-file",
 "log-opts": {
   "max-size": "100m"
 },
 "storage-driver": "overlay2"
  }
EOF
 mkdir -p /etc/systemd/system/docker.service.d
 systemctl daemon-reload
 systemctl restart docker
 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
 apt-get update
 apt-get install -y kubelet kubeadm kubectl
 swapoff -a
  SHELL
end
