Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |p|
        p.name = "master-k8s"
        p.memory = 2048
        p.cpus = 2
  end
  config.vm.hostname = "master-k8s"
  config.vm.network :forwarded_port, guest: 22, host: 3000, id: 'ssh'
  config.vm.network "public_network", ip: "192.168.0.50", bridge: "enp34s0"


  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install net-tools vim curl -y
   curl -fsSL https://get.docker.com/ | bash
   cat > /etc/docker/daemon.json <<EOF
  {
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
   }
EOF
  mkdir -p /etc/systemd/system/docker.service.d
  systemctl daemon-reload
  systemctl restart docker
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  apt-get update
  apt-get install -y kubelet kubeadm kubectl
  swapoff -a
  kubeadm config images pull
  kubeadm init
  mkdir -p $HOME/.kube
  cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  chown $(id -u):$(id -g) $HOME/.kube/config
  modprobe br_netfilter ip_vs_rr ip_vs_wrr ip_vs_sh nf_conntrack_ipv4 ip_vs
  kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  SHELL

end
