Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |p|
        p.name = "no3"
        p.memory = 2048
        p.cpus = 2
  end
  config.vm.hostname = "no3"
  config.vm.network :forwarded_port, guest: 22, host: 3202, id: 'ssh'
  config.vm.network "public_network", ip: "192.168.0.52", bridge: "enp34s0"


  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install net-tools -y
   apt-get install vim -y
   apt-get install curl -y
  SHELL
end
